/**
 * GameEngine – the deterministic central tick loop for Project: Null Pointer.
 *
 * Responsibilities:
 *  • Drive a fixed-interval tick clock (default 1 000 ms / tick).
 *  • Calculate resource deltas each tick (drone mining + server compute).
 *  • Emit a TickEvent to all registered subscribers after each tick.
 *  • Remain completely decoupled from React / UI concerns.
 *
 * Usage:
 *   const engine = new GameEngine();
 *   engine.subscribe(event => console.log(event));
 *   engine.start();
 *   // …later…
 *   engine.stop();
 */

import type { GameState, ResourceId, TickEvent, TickSubscriber } from './types';
import { buildInitialResourceMap } from './resources';

/** Default tick interval in milliseconds. */
const DEFAULT_TICK_MS = 1_000;

export class GameEngine {
  /** Current game state; mutated in place each tick. */
  private state: GameState;

  /** Registered tick-event listeners. */
  private subscribers: Set<TickSubscriber> = new Set();

  /** Reference to the active setInterval handle (Node or browser). */
  private intervalHandle: ReturnType<typeof setInterval> | null = null;

  /** Tick duration in milliseconds. */
  private readonly tickMs: number;

  constructor(tickMs: number = DEFAULT_TICK_MS) {
    this.tickMs = tickMs;
    this.state = GameEngine.buildInitialState();
  }

  // ─── Lifecycle ─────────────────────────────────────────────────────────────

  /** Start the tick loop. Safe to call multiple times (no-op if already running). */
  start(): void {
    if (this.intervalHandle !== null) return;
    this.intervalHandle = setInterval(() => this.tick(), this.tickMs);
  }

  /** Stop the tick loop. Safe to call when already stopped. */
  stop(): void {
    if (this.intervalHandle === null) return;
    clearInterval(this.intervalHandle);
    this.intervalHandle = null;
  }

  /** Returns true while the engine's interval is active. Derived from intervalHandle. */
  get isRunning(): boolean {
    return this.intervalHandle !== null;
  }

  // ─── State ─────────────────────────────────────────────────────────────────

  /** Returns a shallow copy of the current game state (safe to read from UI). */
  getState(): Readonly<GameState> {
    return {
      ...this.state,
      resources: { ...this.state.resources },
      // Derive isRunning from intervalHandle to avoid dual-tracking inconsistency.
      isRunning: this.isRunning,
    };
  }

  /**
   * Register a new drone with the engine.
   * Prefer this over direct mutation of `getState().drones`.
   */
  addDrone(drone: import('./types').DroneData): void {
    this.state.drones = [...this.state.drones, drone];
  }

  /**
   * Directly mutate a resource amount. Use sparingly (cheat / debug / test).
   * Clamps to [0, maxAmount] if a cap is defined in RESOURCE_DEFINITIONS.
   */
  setResource(id: ResourceId, amount: number): void {
    this.state.resources[id] = Math.max(0, amount);
  }

  // ─── Subscriptions ─────────────────────────────────────────────────────────

  /** Register a callback to be called after every tick. */
  subscribe(subscriber: TickSubscriber): () => void {
    this.subscribers.add(subscriber);
    // Return an unsubscribe function for convenience.
    return () => this.subscribers.delete(subscriber);
  }

  /** Unregister a previously registered callback. */
  unsubscribe(subscriber: TickSubscriber): void {
    this.subscribers.delete(subscriber);
  }

  // ─── Core Tick Logic ───────────────────────────────────────────────────────

  /**
   * Process one deterministic tick.
   * Called internally by the interval; also callable directly for testing.
   */
  tick(): void {
    this.state.tick += 1;

    const delta: Partial<Record<ResourceId, number>> = {};
    const heatDelta = this.processModules(delta);
    this.processDrones(delta);
    this.applyDeltas(delta);

    const event: TickEvent = {
      tick: this.state.tick,
      delta,
      heatDelta,
    };

    this.emit(event);
  }

  // ─── Private Subsystem Processors ──────────────────────────────────────────

  /**
   * Grid module processor – calculates compute power generated by server racks
   * and heat changes. Returns the net heatDelta for this tick.
   */
  private processModules(delta: Partial<Record<ResourceId, number>>): number {
    let heatDelta = 0;

    for (const drone of this.state.drones) {
      // Each active server rack drone contributes a flat +1 compute per tick.
      // This will be replaced by real grid traversal in Phase 2.
      if (drone.state === 'mining' && drone.targetResource === 'computePower') {
        delta.computePower = (delta.computePower ?? 0) + drone.miningRate;
        // Servers produce heat proportional to compute output.
        heatDelta += drone.miningRate * 0.1;
      }
    }

    this.state.heatLevel = Math.min(100, Math.max(0, this.state.heatLevel + heatDelta));
    return heatDelta;
  }

  /**
   * Drone processor – drones in 'mining' state add their miningRate
   * of the targetResource to the delta map.
   */
  private processDrones(delta: Partial<Record<ResourceId, number>>): void {
    for (const drone of this.state.drones) {
      if (drone.state === 'mining' && drone.targetResource !== 'computePower') {
        delta[drone.targetResource] =
          (delta[drone.targetResource] ?? 0) + drone.miningRate;
      }
    }
  }

  /** Apply the computed delta map to the state's resource counts. */
  private applyDeltas(delta: Partial<Record<ResourceId, number>>): void {
    for (const [key, value] of Object.entries(delta) as [ResourceId, number][]) {
      this.state.resources[key] = Math.max(0, (this.state.resources[key] ?? 0) + value);
    }
  }

  /** Broadcast a TickEvent to all registered subscribers. */
  private emit(event: TickEvent): void {
    this.subscribers.forEach(sub => sub(event));
  }

  // ─── Static Helpers ────────────────────────────────────────────────────────

  /** Build the zero-state for a new game session. */
  static buildInitialState(): GameState {
    return {
      tick: 0,
      resources: buildInitialResourceMap(),
      drones: [],
      heatLevel: 0,
      isRunning: false,
    };
  }
}

/** Singleton engine instance shared across the app. */
export const gameEngine = new GameEngine();
